name: knowlodge-deploy
run-name: ${{ github.actor }} ğŸš€
on: [push]
jobs:
  Deploy-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
      - name: Vuepress deploy
        uses: jenkey2011/vuepress-deploy@v1.8.1
      - run: bash deploy.sh
      - run: echo "ğŸ This job's status is ${{ job.status }}."
