name: knowlodge-deploy
run-name: ${{ github.actor }} ğŸš€
on: [push]
jobs:
  Deploy-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with: 
          node-version: 16.x
      - run: bash deploy.sh
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          REPO: git@github.com:chenmingkong/chenmingkong.github.io.git
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: master
          FOLDER: docs/.vuepress/dist
      - run: echo "ğŸ This job's status is ${{ job.status }}."
